"""The module's version information."""
__author__ = "Alex Capstick"
__title__ = "aml"
__version__ = "0.0.1"
__doc__ = "Some machine learning code!"
__copyright__ = "2022, Alexander Capstick"
__author_email__ = "alexander.capstick19@imperial.ac.uk"